name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Deps
        run: yarn install
      - name: Builds Project
        run: yarn run build
        env:
          CLONE_TOKEN: ${{ secrets.CLONE_TOKEN }}
      - name: Runs Tests
        run: yarn run test
        env:
          CI: true